[package]
name = "android_seshat_bindings"
version = "0.1.0"

[dependencies]
jni = "0.5.2"
serde_json = "=1.0.61"
seshat = { version = "2.3.0", path = "./seshat" }
uuid = { version = "0.8.2", features = ["v4"] }

[lib]
crate_type = ["dylib"]
