[package]
name = "seshat"
version = "2.3.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "Apache-2.0"
description = "A matrix message logger with full text search support"
readme="README.md"
repository="https://github.com/matrix-org/seshat/"

[features]
default = ["encryption"]
encryption = ["aes-ctr", "crypto-mac", "hmac", "sha2",
              "hkdf", "pbkdf2", "rand", "zeroize", "byteorder"]

[dependencies]
tantivy = "0.12.0"
tinysegmenter = "0.1.1"
fs_extra = "1.2.0"
rusqlite = { version = "0.24.2", features = ["bundled"] }
r2d2_sqlite = "0.17.0"
r2d2 = "0.8.9"
lru-cache = "0.1.2"
uuid = { version = "0.8.2", features = ["v4"] }

aes-ctr = { version = "0.6.0", optional = true }
crypto-mac = { version = "0.10.0", optional = true }
hmac = { version = "0.10.1", optional = true }
sha2 = { version = "0.9.2", optional = true }
hkdf = { version = "0.10.0", optional = true }
pbkdf2 = { version = "0.6.0", optional = true }
rand = { version = "0.8.1", optional = true }
zeroize = { version = "1.2.0", optional = true }
byteorder = { version = "1.4.2", optional = true }

serde_json = "=1.0.61"

# This is pinned because Tantivy used an serde re-export that turned private in
# 1.0.119.

# Relevant serde commit https://github.com/serde-rs/serde/commit/dd1f4b483ee204d58465064f6e5bf5a457543b54
# Tantivy patch that fixes this issue https://github.com/tantivy-search/tantivy/pull/975
serde = { version = "=1.0.118", default-features = false, features = ["derive"] }
thiserror = "1.0.23"

[dev-dependencies]
tempfile = "3.1.0"
lazy_static = "1.4.0"
fake = "2.4.0"
